name: Release

on:
  push:
    tags:
      - "v*.*.*"


defaults:
  run:
    working-directory: ./EXILED

env:
  EXILED_REFERENCES_URL: https://exmod-team.github.io/SL-References/Dev.zip
  EXILED_REFERENCES_PATH: ${{ github.workspace }}/EXILED/References
  EXILED_DLL_ARCHIVER_URL: https://github.com/ExMod-Team/EXILED-DLL-Archiver/releases/latest/download/EXILED-DLL-Archiver.exe

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest
    
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
  
      - name: Setup Nuget
        uses: iRebbok/setup-nuget@master
  
      - uses: actions/checkout@v2.3.4
  
      - name: Get references
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.EXILED_REFERENCES_URL }} -OutFile ${{ github.workspace }}/EXILED/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ env.EXILED_REFERENCES_PATH }}
  
      - name: Build
        env:
          EXILED_REFERENCES: ${{ env.EXILED_REFERENCES_PATH }}
        shell: pwsh
        run: |
          ./build.ps1
          $File = (Get-ChildItem -Path . -Include 'EXILEDOFFICIAL.*.nupkg' -Recurse).Name
          Out-File -FilePath ${{ github.env }} -InputObject "PackageFile=$File" -Encoding utf-8 -Append
          
      - name: Get references
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.EXILED_DLL_ARCHIVER_URL }} -OutFile ${{ github.workspace }}/EXILED/EXILED-DLL-Archiver.exe
    
      - name: Packaging results as tar.gz
        shell: pwsh
        run: ./packaging.ps1

      - name: Install dependencies for Exiled.Installer
        run: dotnet restore Exiled.Installer
  
      - name: Build Exiled.Installer@linux-x64
        run: dotnet publish Exiled.Installer -r linux-x64 -c release -o builds/linux-x64 --self-contained true

      - name: Build Exiled.Installer@win-x64
        run: dotnet publish Exiled.Installer -r win-x64 -c release -o builds/win-x64 --self-contained true
        
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            EXILED/bin/Release/Exiled.tar.gz
            EXILED/builds/win-x64/Exiled.Installer-Win.exe
            EXILED/builds/linux-x64/Exiled.Installer-Linux
      
